apiVersion: v1
kind: Service 
metadata: 
  name: my-pod-service 
  namespace: flux-system
spec: 
  selector:
    project: golang #select pods with this labels in template 
  ports:
    - name: http
      protocol: TCP
      port: 80 #port in loadbalanser 
      targetPort: 8080 #port in pods
